jobs:
  build:
    name: Test Java ${{ matrix.Java }}, ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.6
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/gradle-build-action@v3.3.2
      with:
        arguments: build --scan
    strategy:
      matrix:
        java:
        - '11'
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
name: Build Bisq
on:
  repository_dispatch:
    types: trigger-ga___build.yml
permissions:
  contents: read
